apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

patches:
  - target:
      kind: Route
      name: my-route
    patch: |-
      - op: replace
        path: /spec/to/name
        value: prod-my-service
