apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

namePrefix: dev-

patches:
  - target:
      kind: Route
      name: my-route
    patch: |-
      - op: replace
        path: /spec/to/name
        value: dev-my-service
