apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

patches:
  - target:
      kind: Route
      name: my-route
    patch: |-
      - op: replace
        path: /spec/to/name
        value: dev-my-service
  - target: 
      kind: VirtualMachine
      name: demo-vm-2
    patch: |-
      - op: replace
        path: /spec/running
        value: false
