apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: demo-vm
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: demo-vm-ds-fedora
    spec:
      sourceRef:
        kind: DataSource
        name: fedora
        namespace: openshift-virtualization-os-images
      storage:
        resources: {}
  template:
    metadata:
      labels:
        vm: demo-vm
    spec:
      terminationGracePeriodSeconds: 180
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          rng: {}
          disks:
            - name: cloudinitdisk
              disk:
                bus: virtio
            - name: configmap-disk
              serial: configmap
              volumeName: configmap-volume
        memory:
          guest: 1024M
      volumes:
      - dataVolume:
          name: demo-vm-ds-fedora
        name: demo-vm-ds-fedora
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: fedora
            password: fedora
            chpasswd: { expire: False }
            bootcmd:
              - "mkdir /mnt/myconfigmap"
              - "mount /dev/disk/by-id/ata-QEMU_HARDDISK_configmap /mnt/myconfigmap"
        name: cloudinitdisk
      - name: configmap-volume
        configMap:
          name: vm-startup-script
